// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: authenticate.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Soit.Authentication.Protos {
  public static partial class AuthenticateService
  {
    static readonly string __ServiceName = "Soit.Authentication.AuthenticateService";

    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.LoginRequest> __Marshaller_Soit_Authentication_LoginRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.LoginRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.LoginReply> __Marshaller_Soit_Authentication_LoginReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.LoginReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.TokenRefreshReply> __Marshaller_Soit_Authentication_TokenRefreshReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.TokenRefreshReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Soit.Authentication.Protos.LoginRequest, global::Soit.Authentication.Protos.LoginReply> __Method_Login = new grpc::Method<global::Soit.Authentication.Protos.LoginRequest, global::Soit.Authentication.Protos.LoginReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Login",
        __Marshaller_Soit_Authentication_LoginRequest,
        __Marshaller_Soit_Authentication_LoginReply);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Logout = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Logout",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Soit.Authentication.Protos.TokenRefreshReply> __Method_TokenRefresh = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Soit.Authentication.Protos.TokenRefreshReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TokenRefresh",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_Soit_Authentication_TokenRefreshReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Soit.Authentication.Protos.AuthenticateReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AuthenticateService</summary>
    [grpc::BindServiceMethod(typeof(AuthenticateService), "BindService")]
    public abstract partial class AuthenticateServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Soit.Authentication.Protos.LoginReply> Login(global::Soit.Authentication.Protos.LoginRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Logout(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Soit.Authentication.Protos.TokenRefreshReply> TokenRefresh(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AuthenticateService</summary>
    public partial class AuthenticateServiceClient : grpc::ClientBase<AuthenticateServiceClient>
    {
      /// <summary>Creates a new client for AuthenticateService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AuthenticateServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AuthenticateService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AuthenticateServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AuthenticateServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AuthenticateServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Soit.Authentication.Protos.LoginReply Login(global::Soit.Authentication.Protos.LoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Login(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Soit.Authentication.Protos.LoginReply Login(global::Soit.Authentication.Protos.LoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Login, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Soit.Authentication.Protos.LoginReply> LoginAsync(global::Soit.Authentication.Protos.LoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Soit.Authentication.Protos.LoginReply> LoginAsync(global::Soit.Authentication.Protos.LoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Login, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Logout(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Logout(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Logout(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Logout, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> LogoutAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LogoutAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> LogoutAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Logout, null, options, request);
      }
      public virtual global::Soit.Authentication.Protos.TokenRefreshReply TokenRefresh(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TokenRefresh(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Soit.Authentication.Protos.TokenRefreshReply TokenRefresh(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TokenRefresh, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Soit.Authentication.Protos.TokenRefreshReply> TokenRefreshAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TokenRefreshAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Soit.Authentication.Protos.TokenRefreshReply> TokenRefreshAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TokenRefresh, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AuthenticateServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AuthenticateServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AuthenticateServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Login, serviceImpl.Login)
          .AddMethod(__Method_Logout, serviceImpl.Logout)
          .AddMethod(__Method_TokenRefresh, serviceImpl.TokenRefresh).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AuthenticateServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Login, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Soit.Authentication.Protos.LoginRequest, global::Soit.Authentication.Protos.LoginReply>(serviceImpl.Login));
      serviceBinder.AddMethod(__Method_Logout, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.Logout));
      serviceBinder.AddMethod(__Method_TokenRefresh, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Soit.Authentication.Protos.TokenRefreshReply>(serviceImpl.TokenRefresh));
    }

  }
}
#endregion
