// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: module.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Soit.Authentication.Protos {
  public static partial class ModuleService
  {
    static readonly string __ServiceName = "Soit.Authentication.ModuleService";

    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.CreateModuleRequest> __Marshaller_Soit_Authentication_CreateModuleRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.CreateModuleRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.StringValue> __Marshaller_google_protobuf_StringValue = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.StringValue.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.RemoveModuleRequest> __Marshaller_Soit_Authentication_RemoveModuleRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.RemoveModuleRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.UpdateModuleRequest> __Marshaller_Soit_Authentication_UpdateModuleRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.UpdateModuleRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.GetModuleTreeReply> __Marshaller_Soit_Authentication_GetModuleTreeReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.GetModuleTreeReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.FindModuleReply> __Marshaller_Soit_Authentication_FindModuleReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.FindModuleReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Soit.Authentication.Protos.CreateModuleRequest, global::Google.Protobuf.WellKnownTypes.StringValue> __Method_Create = new grpc::Method<global::Soit.Authentication.Protos.CreateModuleRequest, global::Google.Protobuf.WellKnownTypes.StringValue>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Create",
        __Marshaller_Soit_Authentication_CreateModuleRequest,
        __Marshaller_google_protobuf_StringValue);

    static readonly grpc::Method<global::Soit.Authentication.Protos.RemoveModuleRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Remove = new grpc::Method<global::Soit.Authentication.Protos.RemoveModuleRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Remove",
        __Marshaller_Soit_Authentication_RemoveModuleRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Soit.Authentication.Protos.UpdateModuleRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Update = new grpc::Method<global::Soit.Authentication.Protos.UpdateModuleRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Update",
        __Marshaller_Soit_Authentication_UpdateModuleRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Soit.Authentication.Protos.GetModuleTreeReply> __Method_GetTree = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Soit.Authentication.Protos.GetModuleTreeReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTree",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_Soit_Authentication_GetModuleTreeReply);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Soit.Authentication.Protos.FindModuleReply> __Method_Find = new grpc::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Soit.Authentication.Protos.FindModuleReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Find",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_Soit_Authentication_FindModuleReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Soit.Authentication.Protos.ModuleReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ModuleService</summary>
    [grpc::BindServiceMethod(typeof(ModuleService), "BindService")]
    public abstract partial class ModuleServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.StringValue> Create(global::Soit.Authentication.Protos.CreateModuleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Remove(global::Soit.Authentication.Protos.RemoveModuleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Update(global::Soit.Authentication.Protos.UpdateModuleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Soit.Authentication.Protos.GetModuleTreeReply> GetTree(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Soit.Authentication.Protos.FindModuleReply> Find(global::Google.Protobuf.WellKnownTypes.StringValue request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ModuleService</summary>
    public partial class ModuleServiceClient : grpc::ClientBase<ModuleServiceClient>
    {
      /// <summary>Creates a new client for ModuleService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ModuleServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ModuleService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ModuleServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ModuleServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ModuleServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Google.Protobuf.WellKnownTypes.StringValue Create(global::Soit.Authentication.Protos.CreateModuleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Create(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.StringValue Create(global::Soit.Authentication.Protos.CreateModuleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Create, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.StringValue> CreateAsync(global::Soit.Authentication.Protos.CreateModuleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.StringValue> CreateAsync(global::Soit.Authentication.Protos.CreateModuleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Create, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Remove(global::Soit.Authentication.Protos.RemoveModuleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Remove(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Remove(global::Soit.Authentication.Protos.RemoveModuleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Remove, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> RemoveAsync(global::Soit.Authentication.Protos.RemoveModuleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> RemoveAsync(global::Soit.Authentication.Protos.RemoveModuleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Remove, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Update(global::Soit.Authentication.Protos.UpdateModuleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Update(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Update(global::Soit.Authentication.Protos.UpdateModuleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Update, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateAsync(global::Soit.Authentication.Protos.UpdateModuleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateAsync(global::Soit.Authentication.Protos.UpdateModuleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Update, null, options, request);
      }
      public virtual global::Soit.Authentication.Protos.GetModuleTreeReply GetTree(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTree(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Soit.Authentication.Protos.GetModuleTreeReply GetTree(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTree, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Soit.Authentication.Protos.GetModuleTreeReply> GetTreeAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTreeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Soit.Authentication.Protos.GetModuleTreeReply> GetTreeAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTree, null, options, request);
      }
      public virtual global::Soit.Authentication.Protos.FindModuleReply Find(global::Google.Protobuf.WellKnownTypes.StringValue request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Find(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Soit.Authentication.Protos.FindModuleReply Find(global::Google.Protobuf.WellKnownTypes.StringValue request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Find, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Soit.Authentication.Protos.FindModuleReply> FindAsync(global::Google.Protobuf.WellKnownTypes.StringValue request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FindAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Soit.Authentication.Protos.FindModuleReply> FindAsync(global::Google.Protobuf.WellKnownTypes.StringValue request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Find, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ModuleServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ModuleServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ModuleServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Create, serviceImpl.Create)
          .AddMethod(__Method_Remove, serviceImpl.Remove)
          .AddMethod(__Method_Update, serviceImpl.Update)
          .AddMethod(__Method_GetTree, serviceImpl.GetTree)
          .AddMethod(__Method_Find, serviceImpl.Find).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ModuleServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Create, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Soit.Authentication.Protos.CreateModuleRequest, global::Google.Protobuf.WellKnownTypes.StringValue>(serviceImpl.Create));
      serviceBinder.AddMethod(__Method_Remove, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Soit.Authentication.Protos.RemoveModuleRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.Remove));
      serviceBinder.AddMethod(__Method_Update, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Soit.Authentication.Protos.UpdateModuleRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.Update));
      serviceBinder.AddMethod(__Method_GetTree, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Soit.Authentication.Protos.GetModuleTreeReply>(serviceImpl.GetTree));
      serviceBinder.AddMethod(__Method_Find, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.StringValue, global::Soit.Authentication.Protos.FindModuleReply>(serviceImpl.Find));
    }

  }
}
#endregion
