// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stock.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace StockServices.Protos {
  public static partial class Stock
  {
    static readonly string __ServiceName = "stock.Stock";

    static readonly grpc::Marshaller<global::StockServices.Protos.Empty> __Marshaller_stock_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::StockServices.Protos.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::StockServices.Protos.Product> __Marshaller_stock_Product = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::StockServices.Protos.Product.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::StockServices.Protos.Result> __Marshaller_stock_Result = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::StockServices.Protos.Result.Parser.ParseFrom);

    static readonly grpc::Method<global::StockServices.Protos.Empty, global::StockServices.Protos.Product> __Method_GetAllProducts = new grpc::Method<global::StockServices.Protos.Empty, global::StockServices.Protos.Product>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetAllProducts",
        __Marshaller_stock_Empty,
        __Marshaller_stock_Product);

    static readonly grpc::Method<global::StockServices.Protos.Product, global::StockServices.Protos.Result> __Method_AddProduct = new grpc::Method<global::StockServices.Protos.Product, global::StockServices.Protos.Result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddProduct",
        __Marshaller_stock_Product,
        __Marshaller_stock_Result);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::StockServices.Protos.StockReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Stock</summary>
    [grpc::BindServiceMethod(typeof(Stock), "BindService")]
    public abstract partial class StockBase
    {
      public virtual global::System.Threading.Tasks.Task GetAllProducts(global::StockServices.Protos.Empty request, grpc::IServerStreamWriter<global::StockServices.Protos.Product> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::StockServices.Protos.Result> AddProduct(global::StockServices.Protos.Product request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Stock</summary>
    public partial class StockClient : grpc::ClientBase<StockClient>
    {
      /// <summary>Creates a new client for Stock</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public StockClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Stock that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public StockClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected StockClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected StockClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::StockServices.Protos.Product> GetAllProducts(global::StockServices.Protos.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllProducts(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::StockServices.Protos.Product> GetAllProducts(global::StockServices.Protos.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetAllProducts, null, options, request);
      }
      public virtual global::StockServices.Protos.Result AddProduct(global::StockServices.Protos.Product request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddProduct(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::StockServices.Protos.Result AddProduct(global::StockServices.Protos.Product request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddProduct, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::StockServices.Protos.Result> AddProductAsync(global::StockServices.Protos.Product request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddProductAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::StockServices.Protos.Result> AddProductAsync(global::StockServices.Protos.Product request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddProduct, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override StockClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new StockClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(StockBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAllProducts, serviceImpl.GetAllProducts)
          .AddMethod(__Method_AddProduct, serviceImpl.AddProduct).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, StockBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetAllProducts, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::StockServices.Protos.Empty, global::StockServices.Protos.Product>(serviceImpl.GetAllProducts));
      serviceBinder.AddMethod(__Method_AddProduct, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::StockServices.Protos.Product, global::StockServices.Protos.Result>(serviceImpl.AddProduct));
    }

  }
}
#endregion
