// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: user.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Soit.Authentication.Protos {
  public static partial class UserService
  {
    static readonly string __ServiceName = "Soit.Authentication.UserService";

    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.CreateUserRequest> __Marshaller_Soit_Authentication_CreateUserRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.CreateUserRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.StringValue> __Marshaller_google_protobuf_StringValue = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.StringValue.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.RemoveUserRequest> __Marshaller_Soit_Authentication_RemoveUserRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.RemoveUserRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.UpdateUserRequest> __Marshaller_Soit_Authentication_UpdateUserRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.UpdateUserRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.QueryUserRequest> __Marshaller_Soit_Authentication_QueryUserRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.QueryUserRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.QueryUserReply> __Marshaller_Soit_Authentication_QueryUserReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.QueryUserReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.FindUserReply> __Marshaller_Soit_Authentication_FindUserReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.FindUserReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.UpdateUserNameRequest> __Marshaller_Soit_Authentication_UpdateUserNameRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.UpdateUserNameRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.ResetPasswordRequest> __Marshaller_Soit_Authentication_ResetPasswordRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.ResetPasswordRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.UpdatePasswordRequest> __Marshaller_Soit_Authentication_UpdatePasswordRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.UpdatePasswordRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.UpdateUserRolesRequest> __Marshaller_Soit_Authentication_UpdateUserRolesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.UpdateUserRolesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.UpdateUserOrganizationsRequest> __Marshaller_Soit_Authentication_UpdateUserOrganizationsRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.UpdateUserOrganizationsRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Soit.Authentication.Protos.UpdateUserStatesRequest> __Marshaller_Soit_Authentication_UpdateUserStatesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Soit.Authentication.Protos.UpdateUserStatesRequest.Parser.ParseFrom);

    static readonly grpc::Method<global::Soit.Authentication.Protos.CreateUserRequest, global::Google.Protobuf.WellKnownTypes.StringValue> __Method_Create = new grpc::Method<global::Soit.Authentication.Protos.CreateUserRequest, global::Google.Protobuf.WellKnownTypes.StringValue>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Create",
        __Marshaller_Soit_Authentication_CreateUserRequest,
        __Marshaller_google_protobuf_StringValue);

    static readonly grpc::Method<global::Soit.Authentication.Protos.RemoveUserRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Remove = new grpc::Method<global::Soit.Authentication.Protos.RemoveUserRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Remove",
        __Marshaller_Soit_Authentication_RemoveUserRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Soit.Authentication.Protos.UpdateUserRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Update = new grpc::Method<global::Soit.Authentication.Protos.UpdateUserRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Update",
        __Marshaller_Soit_Authentication_UpdateUserRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Soit.Authentication.Protos.QueryUserRequest, global::Soit.Authentication.Protos.QueryUserReply> __Method_Query = new grpc::Method<global::Soit.Authentication.Protos.QueryUserRequest, global::Soit.Authentication.Protos.QueryUserReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Query",
        __Marshaller_Soit_Authentication_QueryUserRequest,
        __Marshaller_Soit_Authentication_QueryUserReply);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Soit.Authentication.Protos.FindUserReply> __Method_Find = new grpc::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Soit.Authentication.Protos.FindUserReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Find",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_Soit_Authentication_FindUserReply);

    static readonly grpc::Method<global::Soit.Authentication.Protos.UpdateUserNameRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateName = new grpc::Method<global::Soit.Authentication.Protos.UpdateUserNameRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateName",
        __Marshaller_Soit_Authentication_UpdateUserNameRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Soit.Authentication.Protos.ResetPasswordRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ResetPassword = new grpc::Method<global::Soit.Authentication.Protos.ResetPasswordRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ResetPassword",
        __Marshaller_Soit_Authentication_ResetPasswordRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Soit.Authentication.Protos.UpdatePasswordRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdatePassword = new grpc::Method<global::Soit.Authentication.Protos.UpdatePasswordRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdatePassword",
        __Marshaller_Soit_Authentication_UpdatePasswordRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Soit.Authentication.Protos.UpdateUserRolesRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateRoles = new grpc::Method<global::Soit.Authentication.Protos.UpdateUserRolesRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateRoles",
        __Marshaller_Soit_Authentication_UpdateUserRolesRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Soit.Authentication.Protos.UpdateUserOrganizationsRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateOrganizations = new grpc::Method<global::Soit.Authentication.Protos.UpdateUserOrganizationsRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateOrganizations",
        __Marshaller_Soit_Authentication_UpdateUserOrganizationsRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Soit.Authentication.Protos.UpdateUserStatesRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateStates = new grpc::Method<global::Soit.Authentication.Protos.UpdateUserStatesRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateStates",
        __Marshaller_Soit_Authentication_UpdateUserStatesRequest,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Soit.Authentication.Protos.UserReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of UserService</summary>
    [grpc::BindServiceMethod(typeof(UserService), "BindService")]
    public abstract partial class UserServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.StringValue> Create(global::Soit.Authentication.Protos.CreateUserRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Remove(global::Soit.Authentication.Protos.RemoveUserRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Update(global::Soit.Authentication.Protos.UpdateUserRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Soit.Authentication.Protos.QueryUserReply> Query(global::Soit.Authentication.Protos.QueryUserRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Soit.Authentication.Protos.FindUserReply> Find(global::Google.Protobuf.WellKnownTypes.StringValue request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> UpdateName(global::Soit.Authentication.Protos.UpdateUserNameRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> ResetPassword(global::Soit.Authentication.Protos.ResetPasswordRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> UpdatePassword(global::Soit.Authentication.Protos.UpdatePasswordRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> UpdateRoles(global::Soit.Authentication.Protos.UpdateUserRolesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> UpdateOrganizations(global::Soit.Authentication.Protos.UpdateUserOrganizationsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> UpdateStates(global::Soit.Authentication.Protos.UpdateUserStatesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for UserService</summary>
    public partial class UserServiceClient : grpc::ClientBase<UserServiceClient>
    {
      /// <summary>Creates a new client for UserService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UserServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UserService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UserServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UserServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UserServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Google.Protobuf.WellKnownTypes.StringValue Create(global::Soit.Authentication.Protos.CreateUserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Create(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.StringValue Create(global::Soit.Authentication.Protos.CreateUserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Create, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.StringValue> CreateAsync(global::Soit.Authentication.Protos.CreateUserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.StringValue> CreateAsync(global::Soit.Authentication.Protos.CreateUserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Create, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Remove(global::Soit.Authentication.Protos.RemoveUserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Remove(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Remove(global::Soit.Authentication.Protos.RemoveUserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Remove, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> RemoveAsync(global::Soit.Authentication.Protos.RemoveUserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> RemoveAsync(global::Soit.Authentication.Protos.RemoveUserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Remove, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Update(global::Soit.Authentication.Protos.UpdateUserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Update(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Update(global::Soit.Authentication.Protos.UpdateUserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Update, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateAsync(global::Soit.Authentication.Protos.UpdateUserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateAsync(global::Soit.Authentication.Protos.UpdateUserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Update, null, options, request);
      }
      public virtual global::Soit.Authentication.Protos.QueryUserReply Query(global::Soit.Authentication.Protos.QueryUserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Query(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Soit.Authentication.Protos.QueryUserReply Query(global::Soit.Authentication.Protos.QueryUserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Query, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Soit.Authentication.Protos.QueryUserReply> QueryAsync(global::Soit.Authentication.Protos.QueryUserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Soit.Authentication.Protos.QueryUserReply> QueryAsync(global::Soit.Authentication.Protos.QueryUserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Query, null, options, request);
      }
      public virtual global::Soit.Authentication.Protos.FindUserReply Find(global::Google.Protobuf.WellKnownTypes.StringValue request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Find(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Soit.Authentication.Protos.FindUserReply Find(global::Google.Protobuf.WellKnownTypes.StringValue request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Find, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Soit.Authentication.Protos.FindUserReply> FindAsync(global::Google.Protobuf.WellKnownTypes.StringValue request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FindAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Soit.Authentication.Protos.FindUserReply> FindAsync(global::Google.Protobuf.WellKnownTypes.StringValue request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Find, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateName(global::Soit.Authentication.Protos.UpdateUserNameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateName(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateName(global::Soit.Authentication.Protos.UpdateUserNameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateName, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateNameAsync(global::Soit.Authentication.Protos.UpdateUserNameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateNameAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateNameAsync(global::Soit.Authentication.Protos.UpdateUserNameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateName, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty ResetPassword(global::Soit.Authentication.Protos.ResetPasswordRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ResetPassword(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty ResetPassword(global::Soit.Authentication.Protos.ResetPasswordRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ResetPassword, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> ResetPasswordAsync(global::Soit.Authentication.Protos.ResetPasswordRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ResetPasswordAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> ResetPasswordAsync(global::Soit.Authentication.Protos.ResetPasswordRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ResetPassword, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdatePassword(global::Soit.Authentication.Protos.UpdatePasswordRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdatePassword(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdatePassword(global::Soit.Authentication.Protos.UpdatePasswordRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdatePassword, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdatePasswordAsync(global::Soit.Authentication.Protos.UpdatePasswordRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdatePasswordAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdatePasswordAsync(global::Soit.Authentication.Protos.UpdatePasswordRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdatePassword, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateRoles(global::Soit.Authentication.Protos.UpdateUserRolesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateRoles(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateRoles(global::Soit.Authentication.Protos.UpdateUserRolesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateRoles, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateRolesAsync(global::Soit.Authentication.Protos.UpdateUserRolesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateRolesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateRolesAsync(global::Soit.Authentication.Protos.UpdateUserRolesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateRoles, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateOrganizations(global::Soit.Authentication.Protos.UpdateUserOrganizationsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateOrganizations(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateOrganizations(global::Soit.Authentication.Protos.UpdateUserOrganizationsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateOrganizations, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateOrganizationsAsync(global::Soit.Authentication.Protos.UpdateUserOrganizationsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateOrganizationsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateOrganizationsAsync(global::Soit.Authentication.Protos.UpdateUserOrganizationsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateOrganizations, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateStates(global::Soit.Authentication.Protos.UpdateUserStatesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateStates(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateStates(global::Soit.Authentication.Protos.UpdateUserStatesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateStates, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateStatesAsync(global::Soit.Authentication.Protos.UpdateUserStatesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateStatesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateStatesAsync(global::Soit.Authentication.Protos.UpdateUserStatesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateStates, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UserServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UserServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(UserServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Create, serviceImpl.Create)
          .AddMethod(__Method_Remove, serviceImpl.Remove)
          .AddMethod(__Method_Update, serviceImpl.Update)
          .AddMethod(__Method_Query, serviceImpl.Query)
          .AddMethod(__Method_Find, serviceImpl.Find)
          .AddMethod(__Method_UpdateName, serviceImpl.UpdateName)
          .AddMethod(__Method_ResetPassword, serviceImpl.ResetPassword)
          .AddMethod(__Method_UpdatePassword, serviceImpl.UpdatePassword)
          .AddMethod(__Method_UpdateRoles, serviceImpl.UpdateRoles)
          .AddMethod(__Method_UpdateOrganizations, serviceImpl.UpdateOrganizations)
          .AddMethod(__Method_UpdateStates, serviceImpl.UpdateStates).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, UserServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Create, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Soit.Authentication.Protos.CreateUserRequest, global::Google.Protobuf.WellKnownTypes.StringValue>(serviceImpl.Create));
      serviceBinder.AddMethod(__Method_Remove, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Soit.Authentication.Protos.RemoveUserRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.Remove));
      serviceBinder.AddMethod(__Method_Update, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Soit.Authentication.Protos.UpdateUserRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.Update));
      serviceBinder.AddMethod(__Method_Query, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Soit.Authentication.Protos.QueryUserRequest, global::Soit.Authentication.Protos.QueryUserReply>(serviceImpl.Query));
      serviceBinder.AddMethod(__Method_Find, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.StringValue, global::Soit.Authentication.Protos.FindUserReply>(serviceImpl.Find));
      serviceBinder.AddMethod(__Method_UpdateName, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Soit.Authentication.Protos.UpdateUserNameRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.UpdateName));
      serviceBinder.AddMethod(__Method_ResetPassword, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Soit.Authentication.Protos.ResetPasswordRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.ResetPassword));
      serviceBinder.AddMethod(__Method_UpdatePassword, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Soit.Authentication.Protos.UpdatePasswordRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.UpdatePassword));
      serviceBinder.AddMethod(__Method_UpdateRoles, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Soit.Authentication.Protos.UpdateUserRolesRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.UpdateRoles));
      serviceBinder.AddMethod(__Method_UpdateOrganizations, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Soit.Authentication.Protos.UpdateUserOrganizationsRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.UpdateOrganizations));
      serviceBinder.AddMethod(__Method_UpdateStates, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Soit.Authentication.Protos.UpdateUserStatesRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.UpdateStates));
    }

  }
}
#endregion
